 name: Test

on: [push]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
        matrix:
            os: [ubuntu-latest] # windows not added due to || operator not being valid
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - name: test
        run: |
          npm run lint
          npm test
        env:
          CI: true
